feat(setup): add validation to not commit directly to main branch

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,6 +1,13 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "main" ]; then
+  echo "You can't commit directly to master branch"
+  exit 1
+fi
+
 flutter test
 dart format . -l 120 --set-exit-if-changed
 dart analyze --fatal-infos --fatal-warnings .
